### ISSUE TITLE
Build fails with Gradle M7

### ISSUE THREAD

**Issue by harschware** [stigkj/gradle-executable-jar-plugin#10]
After adding the snippet from the README my otherwise working build produces the following error.

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/Factory at 
org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:94)
    ... 52 more
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.Factory
    ... 53 more

BUILD FAILED
```

**Comment by harschware** [comment]
To rule out side effects from my build I created a build.gradle containing only the suggested code from the README.md.  I get the same error.

**Comment by stigkj** [comment]
hmm...strange. Do you have a complete stacktrace? This does not show any of my code. Just put -s on the gradle command line.

**Comment by harschware** [comment]
I just tested again, this time on my fairly virgin Mac Book Pro (previous test was on Win7 box).  I got the output below.  Do you maybe have some environment in your .gradle/init.gradle or something?

Tims-MacBook-Pro:gradle-license-test tharsch$ gradle build -s
Download http://repo1.maven.org/maven2/net/nisgits/gradle/gradle-executable-jar-plugin/master-REL-5/gradle-executable-jar-plugin-master-REL-5.pom
Download http://repo1.maven.org/maven2/net/nisgits/gradle/gradle-executable-jar-plugin/master-REL-5/gradle-executable-jar-plugin-master-REL-5.jar

FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/tharsch/t/gradle-license-test/build.gradle' line: 1
- What went wrong:
  A problem occurred evaluating root project 'gradle-license-test'.
  Cause: Could not generate a proxy class for class net.nisgits.gradle.executablejar.ExecutableJar.
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'gradle-license-test'.
  at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
  at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:127)
  at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
  at org.gradle.configuration.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:43)
  at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:475)
  at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:74)
  at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:23)
  at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:21)
  at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuildConfigurer.java:38)
  at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuildConfigurer.java:35)
  at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:451)
  at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:446)
  at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:137)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:108)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:76)
  at org.gradle.launcher.cli.RunBuildAction.execute(RunBuildAction.java:42)
  at org.gradle.launcher.cli.RunBuildAction.execute(RunBuildAction.java:28)
  at org.gradle.launcher.exec.ExceptionReportingAction.execute(ExceptionReportingAction.java:32)
  at org.gradle.launcher.exec.ExceptionReportingAction.execute(ExceptionReportingAction.java:21)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory.java:238)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory.java:222)
  at org.gradle.launcher.Main.doAction(Main.java:48)
  at org.gradle.launcher.exec.EntryPoint$1.execute(EntryPoint.java:53)
  at org.gradle.launcher.exec.EntryPoint$1.execute(EntryPoint.java:51)
  at org.gradle.launcher.exec.Execution.execute(Execution.java:28)
  at org.gradle.launcher.exec.EntryPoint.run(EntryPoint.java:39)
  at org.gradle.launcher.Main.main(Main.java:39)
  at org.gradle.launcher.ProcessBootstrap.runNoExit(ProcessBootstrap.java:51)
  at org.gradle.launcher.ProcessBootstrap.run(ProcessBootstrap.java:33)
  at org.gradle.launcher.GradleMain.main(GradleMain.java:24)
  Caused by: org.gradle.api.GradleException: Could not generate a proxy class for class net.nisgits.gradle.executablejar.ExecutableJar.
  at org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:187)
  at org.gradle.api.internal.project.taskfactory.TaskFactory.createTaskObject(TaskFactory.java:90)
  at org.gradle.api.internal.project.taskfactory.TaskFactory.createTask(TaskFactory.java:55)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.createTask(AnnotationProcessingTaskFactory.java:64)
  at org.gradle.api.internal.project.taskfactory.DependencyAutoWireTaskFactory.createTask(DependencyAutoWireTaskFactory.java:39)
  at org.gradle.api.internal.tasks.DefaultTaskContainer.add(DefaultTaskContainer.java:49)
  at org.gradle.api.internal.tasks.DefaultTaskContainer.add(DefaultTaskContainer.java:72)
  at org.gradle.api.tasks.TaskContainer$add.call(Unknown Source)
  at net.nisgits.gradle.executablejar.ExecutableJarPlugin.apply(ExecutableJarPlugin.groovy:75)
  at net.nisgits.gradle.executablejar.ExecutableJarPlugin.apply(ExecutableJarPlugin.groovy)
  at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.providePlugin(DefaultProjectsPluginContainer.java:107)
  at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.addPluginInternal(DefaultProjectsPluginContainer.java:71)
  at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.apply(DefaultProjectsPluginContainer.java:37)
  at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:101)
  at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:32)
  at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:72)
  at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:114)
  at org.gradle.api.internal.project.AbstractProject.apply(AbstractProject.java:846)
  at org.gradle.api.Project$apply.call(Unknown Source)
  at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:35)
  at org.gradle.api.Script$apply.callCurrent(Unknown Source)
  at build_7qr86vgtikil6svdai191odel4.run(/Users/tharsch/t/gradle-license-test/build.gradle:1)
  at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
  ... 30 more
  Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/Factory
  at org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:94)
  ... 52 more
  Caused by: java.lang.ClassNotFoundException: org.gradle.internal.Factory
  ... 53 more

BUILD FAILED

Total time: 4.744 secs

**Comment by harschware** [comment]
One more peg point for you: Running this gradle.build with gradle-M6 works, with M7 fails for the CommonsHttpClientResolver problem.  Note this build is using REL-4.  If I attempt to use REL-5 with gradle M6 it fails same as with M7.

```
apply plugin: 'executable-jar'

mainClass = 'call.with.Main'

buildscript {
    repositories {
        mavenCentral()
   }
    dependencies {
        classpath 'net.nisgits.gradle:gradle-executable-jar-plugin:master-REL-4'
   }
}
```

**Comment by stigkj** [comment]
Sorry about this. I have managed to build the release with a milestone-8 snapshot release of gradle. A new version (master-REL-6) built with milestone-7 is on it way up to Maven Central.

**Comment by harschware** [comment]
No problem, thanks for the great plugin.

**Comment by eegasudheer** [comment]
I try apply == > apply plugin: 'executable-jar' in my script . After executing below script, jar file generated successfully inside /build/libs. when I try to run the jar file I'm getting 

Exception in thread "main" java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at com.simontuffs.onejar.JarClassLoader.defineClass(JarClassLoader.java:803)
        at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:710)

# Below is the script 

apply plugin: 'executable-jar'

mainClass = 'hello'

buildscript {
    repositories {
        mavenCentral()
   }
    dependencies {

```
    classpath 'net.nisgits.gradle:gradle-executable-jar-plugin:master-REL-6' , 'org.codehaus.groovy:groovy-all:1.7.10'      
```

   }
}

I'm running the jar with 

java -jar <jarfilename>

Not sure what was the the problem.

**Comment by stigkj** [comment]
Is this an application written in Groovy? Remember that the `dependencies` section inside the `buildscript` section is only for running the executable-jar plugin and won't be included in the resulting jar file.

And could you please move this to a new issue?
